### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by Pakhiou** [yui-10497108108111/MD-CN-Translator#1]
作者大佬你好，感谢您制作游戏王md的汉化插件，对我这个新手帮助很大。👍👍
不过插件好像有一些小瑕疵，比如灵摆怪兽的灵摆效果无法正常显示，如下图：
还有 能不能增加自定义插件窗口的大小的功能，非常感谢！

![image](https://user-images.githubusercontent.com/82596959/150913444-6b7fa17e-f066-421d-b440-341aa0e2e09b.png)

**Comment by yui-10497108108111** [comment]
已修复
